### ISSUE TITLE
Result are truncated[BUG] 

### ISSUE THREAD

**Issue by shivamn** [bleroy/lunr-core#52]
var index = await Lunr.Index.Build(async builder =>
{
    builder
        .AddField("country")
        .AddField("state")
        .AddField("district")
         .AddField("city")
        .AddField("area")
        .AddField("postalcode");

    await builder.Add(new Document
                {
                    { "country", "india" },
                    { "state", "karnataka" },
                    { "district", "" },
                    { "city", "Bangalore" },
                    {"area","Malleshwaram" },
                    { "postalcode","560003" },
                    { "id", "1" }
                });

    await builder.Add(new Document
                {
                    { "country", "india" },
                    { "state", "karnataka" },
                    { "district", "" },
                    { "city", "Bangalore" },
                    {"area","Jayanagar" },
                    { "postalcode","560008" },
                    { "id", "2" }
                });
});

await foreach (Result result in index.Search(" Malleshwaram, bangalore india"))
{

   // match data contains only "bangalor " insted of "bangalore" 
}

**Comment by bleroy** [comment]
"bangalor" is the key in the inverted index, not the text for the match. Because it's an inverted index entry, what you get is the stemmed version of the term, not the matched text.

In order to get the full data for the matches, you need to add a little incantation to your builder code, right after defining the fields:

```csharp
builder.MetadataAllowList.Add("position");
```

Once you've done that, you'll see that results have additional positional data for the match:
![image](https://github.com/bleroy/lunr-core/assets/1165609/ef5e9265-ee3e-4b69-aa9f-984731222d09)

What this is showing you is that you have a match on the "city" field at position 0, with a length of 9. That accurately gives you "Bangalore" if you fetch the document and take the relevant substring (which happens to be the full string in this case, but you see the idea for more elaborate documents...)
